#!/usr/bin/env bash

code --install-extension Cronos87.symfony-snippets
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension ikappas.phpcs
code --install-extension junstyle.php-cs-fixer
code --install-extension marcostazi.VS-code-vagrantfile
code --install-extension mikestead.dotenv
code --install-extension neilbrayfield.php-docblocker
code --install-extension phproberto.vscode-php-getters-setters
code --install-extension whatwedo.twig