#!/usr/bin/env bash

code --install-extension alexkrechik.cucumberautocomplete
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension Cronos87.symfony-snippets
code --install-extension eamodio.gitlens
code --install-extension golang.go
code --install-extension ikappas.phpcs
code --install-extension jebbs.plantuml
code --install-extension junstyle.php-cs-fixer
code --install-extension marcostazi.VS-code-vagrantfile
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension neilbrayfield.php-docblocker
code --install-extension phproberto.vscode-php-getters-setters
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension vivaxy.vscode-conventional-commits
code --install-extension whatwedo.twig
